Repository GYOUDNova/Nova, pull requests merged in 2025-08, with the labels that each got.

#90 Directional gesture recognition
  Assets/Prefabs.meta
  Assets/Prefabs/Gesture Recognizer.prefab
  Assets/Prefabs/Gesture Recognizer.prefab.meta
  Assets/Scenes/Main Scene.unity
  Assets/Scripts/Controllers/CreatingGestureWindowController.cs
  Assets/Scripts/Controllers/GestureInputController.cs
  Assets/Scripts/Controllers/MainEditorWindowController.cs
  Assets/Scripts/Database/GestureSqliteHandler.cs
  Assets/Scripts/Database/LandmarkAngle.cs
  Assets/Scripts/Database/LandmarkAngle.cs.meta
  Assets/Scripts/Database/LandmarkDirection.cs
  Assets/Scripts/Database/LandmarkDirection.cs.meta
  Assets/Scripts/Helpers/ResetLocalState.cs
  Assets/Scripts/Mediapipe/GestureRecognizer.cs
  Assets/Scripts/Mediapipe/HandLandmarkerRunner.cs
  Assets/Scripts/Mediapipe/UI/Objects/Main Canvas.prefab
  Assets/Scripts/PlayerInput.cs
  Assets/Tests/Edit Mode Tests/GestureSqliteHandlerTests.cs
  Assets/Tests/Play Mode Tests/GestureInputControllerTests.cs
  NOVA.csproj
Labels: feature, enhancement

#93 Nova - Add Predefined Gestures
  Assets/Samples/Rollaball/MiniGame.unity
  Assets/Scripts/Controllers/CreatingGestureWindowController.cs
  Assets/Scripts/Controllers/GestureInputController.cs
  Assets/Scripts/Controllers/GestureListWindowController.cs
  Assets/Scripts/Controllers/MainEditorWindowController.cs
  Assets/Scripts/Controllers/NovaMediapipeHandler.cs
  Assets/Scripts/Controllers/NovaMediapipeHandler.cs.meta
  Assets/Scripts/Database/GestureCategory.cs
  Assets/Scripts/Database/GestureSqliteHandler.cs
  Assets/Scripts/Helpers/AddPredefinedGesturesHelper.cs
  Assets/Scripts/Helpers/AddPredefinedGesturesHelper.cs.meta
  Assets/Scripts/Helpers/HelperConstants.cs
  Assets/StreamingAssets/GestureAssets/Images.meta
  Assets/StreamingAssets/GestureAssets/Images/closed fist l.jpeg
  Assets/StreamingAssets/GestureAssets/Images/closed fist l.jpeg.meta
  Assets/StreamingAssets/GestureAssets/Images/one finger l.jpeg
  Assets/StreamingAssets/GestureAssets/Images/one finger l.jpeg.meta
  Assets/StreamingAssets/GestureAssets/Images/open palm l.jpeg
  Assets/StreamingAssets/GestureAssets/Images/open palm l.jpeg.meta
  Assets/StreamingAssets/GestureAssets/Images/peace sign l.jpeg
  Assets/StreamingAssets/GestureAssets/Images/peace sign l.jpeg.meta
  Assets/UI Toolkit/Gesture List Window/GestureContainerUSS.uss
  Assets/UI Toolkit/Main Editor Window/MainEditorWindow.uxml
  NOVA.csproj
Labels: enhancement

#94 Update Readme
  README.md
Labels: feature, enhancement

#97 fix: delete gesture image based on IsPredefined flag
  Assets/Scripts/Database/GestureSqliteHandler.cs
Labels: bug
